version: "3.8"

services:
  ngrok:
    build: .
    image: zhaopan/ngrok
    container_name: ngrok-server
    restart: always
    ports:
      - "80:80" # 80
      - "443:443" # 443
      - "4443:4443" # 4443
      - "3389:3389" # 3389
      - "8080:8080" # 8080
    volumes:
      - ${NGROK_DATA_DIR}:/myfiles
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/sh /server.sh
